name: Calculator

on:
  push:
    branches:[ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: action/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed main.py

      - name: Upload EXE to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: dist/main.exe