name: Calculator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'  # Specify your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed main.py

      - name: Upload EXE to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: dist/main.exe
